//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movie_Collection.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Movie_Collection.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить актера.
        /// </summary>
        public static string AddActorViewModel_DisplayName {
            get {
                return ResourceManager.GetString("AddActorViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить режиссера.
        /// </summary>
        public static string AddDirectorViewModel_DisplayName {
            get {
                return ResourceManager.GetString("AddDirectorViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить фильм.
        /// </summary>
        public static string AddMovieViewModel_DisplayName {
            get {
                return ResourceManager.GetString("AddMovieViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить студию.
        /// </summary>
        public static string AddStudioViewModel_DisplayName {
            get {
                return ResourceManager.GetString("AddStudioViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Актеры.
        /// </summary>
        public static string AllActorsViewModel_DisplayName {
            get {
                return ResourceManager.GetString("AllActorsViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режиссеры.
        /// </summary>
        public static string AllDirectorsViewModel_DisplayName {
            get {
                return ResourceManager.GetString("AllDirectorsViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Жанры.
        /// </summary>
        public static string AllGenresViewModel_DisplayName {
            get {
                return ResourceManager.GetString("AllGenresViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильмы.
        /// </summary>
        public static string AllMoviesViewModel_DisplayName {
            get {
                return ResourceManager.GetString("AllMoviesViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Студии.
        /// </summary>
        public static string AllStudiosViewModel_DisplayName {
            get {
                return ResourceManager.GetString("AllStudiosViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить актера.
        /// </summary>
        public static string MainWindowViewModel_Command_AddActor {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_AddActor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить режиссера.
        /// </summary>
        public static string MainWindowViewModel_Command_AddDirector {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_AddDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить фильм.
        /// </summary>
        public static string MainWindowViewModel_Command_AddMovie {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_AddMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить студию.
        /// </summary>
        public static string MainWindowViewModel_Command_AddStudio {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_AddStudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все актеры.
        /// </summary>
        public static string MainWindowViewModel_Command_ViewAllActors {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewAllActors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все режиссеры.
        /// </summary>
        public static string MainWindowViewModel_Command_ViewAllDirectors {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewAllDirectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все жанры.
        /// </summary>
        public static string MainWindowViewModel_Command_ViewAllGenres {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewAllGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все фильмы.
        /// </summary>
        public static string MainWindowViewModel_Command_ViewAllMovies {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewAllMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все накопители.
        /// </summary>
        public static string MainWindowViewModel_Command_ViewAllStorages {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewAllStorages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все студии.
        /// </summary>
        public static string MainWindowViewModel_Command_ViewAllStudios {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewAllStudios", resourceCulture);
            }
        }
    }
}
